In [2]:
import csv
import matplotlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score


/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [86]:
def read_files():
    global hero, test, train, sample
    hero = pd.read_csv('Data/MatchDetail.csv')
    test = pd.read_csv('Data/MatchOverviewTest.csv')
    train = pd.read_csv('Data/MatchOverviewTraining.csv')
    sample = pd.read_csv('Data/sampleSubmission.csv')
    train.index = train.match_id.tolist()
    del train['match_id']
read_files()
train[(24<train)&(train<108)] -= 1
train[(108 < train) & (train < 114)] -= 2
train.loc[:,'hero_6':'hero_10'] += 111
length = len(train)
X = pd.DataFrame({i:[0 for _ in range(length)] for i in range(1, 223)}, index = train.index)
for index, row in train.iterrows():
    for hero_id in row.tolist()[:10]:
        X.loc[index, hero_id] = 1
y = train.first_5_won.astype('int')


In [87]:
ycopy = y.copy()
Xcopy = X.copy()

In [167]:
y = ycopy.copy()
X = Xcopy.copy()

In [ ]:
def sigmoid(x, deriv = False):
    if deriv:
        return x * (1-x)
    else:
        return 1 / (1 + np.exp(-x))
bias = np.ones((X.shape[0], 1))
X = np.hstack((X, bias))
y = y.T
try:
    y = np.array([y.values]).T
    X = X.values
except:
    pass
first_weights = 2 * np.random.random((X.shape[1], 220)) - 1
second_weights = 2 * np.random.random((220, 1)) - 1
high = 6000
learning_rate = 1
momentum = float(input("Momentum?\n"))
first_past_update = 0
second_past_update = 0
for j in range(high + 1):
    first_neurons = sigmoid(np.dot(X,first_weights))
    second_neurons = sigmoid(np.dot(first_neurons,second_weights))
    second_error = y - second_neurons
    if j % 100 == 0:
        print("Error:" + str(np.mean(np.abs(second_error))))
        learning_rate = float(input("Learning rate?\n"))
    second_delta = (second_error) * (sigmoid(second_neurons, deriv = True))
    first_error = (second_delta).dot(second_weights.T)
    first_delta = first_error * (sigmoid(first_neurons, deriv = True))
    first_update = learning_rate * X.T.dot(first_delta) + momentum * first_past_update
    second_update = learning_rate * first_neurons.T.dot(second_delta) + momentum * second_past_update
    first_weights += first_update
    second_weights += second_update
    first_past_update, second_past_update = first_update.copy(), second_update.copy()
    
print("done")

Momentum?
.5
Error:0.56099463448
Learning rate?
1
Error:0.4163
Learning rate?
1
Error:0.4163


In [157]:
second_neurons

array([[ 1.],
       [ 1.],
       [ 1.],
       ..., 
       [ 1.],
       [ 1.],
       [ 1.]])

In [149]:
np.ones((10, 1))

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [126]:
np.hstack((a,np.random.random((3,1))))

array([[ 0.05506378,  0.33880298,  0.86775971,  0.67607961,  0.31952278],
       [ 0.59101454,  0.03124705,  0.40265468,  0.96404362,  0.95787693],
       [ 0.64682719,  0.04059491,  0.794938  ,  0.69731336,  0.5813147 ]])